theme: jekyll-theme-minimal

paginate: 10
plugins: [jekyll-paginate]
paginate_path: "news/:num/"

language: nl-nl

title: DIVD
description: Het Nederlandse meldpunt voor kwetsbaarheden, infecties en andere (cyber)security gerelateerde zaken.
repository: DIVD-NL/sites

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: false

sass:
  sass_dir: assets/sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-secinfo

collections:
  team:
    output: true
  cases:
    output: false
  cves:
    output: false
  csirt_posts:
    output: false
    permalink: "/:year/:month/:day/:title/"

# Custom headers
webrick:
  headers:
    Content-Security-Policy: "default-src 'none'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.paypal.com https://www.paypalobjects.com; script-src 'self' ; style-src 'self' https://fonts.googleapis.com/; connect-src 'self';"

exclude:
  - README.md
  - serve*
  - "*.sh"
  - "Gemfile*"
  - "*.conf"
