name: build_website
run-name: Build, test and deply website
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
      - run: ./update.sh
      - run:  jekyll build  --future 2>&1 | tee jekyll-build.log

