name: build_website
run-name: Build, test and deploy (on main)
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6' 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: ./update.sh
      - run: rm -rf _cases/3000 _cves/CVE-3000-*
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - run: sudo apt-get update -y && sudo apt-get install libcurl4 -y
      - run: pip3 install html5validator 
      - run: gem install --no-document html-proofer
      - run: ./proof_html.sh
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: _site/**
          retention-days: 1
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Download html
        uses: actions/download-artifact@v3
        with:
          name: html
      - run: ls
      - name: Deploy with rsync
        uses: BuildPC/rsync-with-ssh-github-actions@master
        env:
          HELLO: cool
          MESSAGE: hello world
        with:
          key: ${{ secrets.DEPLOY_KEY_CSIRT }}
          host: ${{ secrets.DEPLOY_HOST }}
          port: 22
          user: ${{ secrets.DEPLOY_USER }}
          destination: htdocs/csirt-divd-nl2
          # runs this on remove server
          ssh_before: |
            echo $HELLO
            echo $MESSAGE
            ls -lath
          # then run these commands
          ssh_after: |
            echo $HELLO
            echo $MESSAGE
            ls -lath