name: build_website
run-name: Build, test and deply website native
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6' 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: ./update.sh
      - run: rm -rf _cases/3000
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - run: sudo apt-get update -y && sudo apt-get install libcurl4 -y
      - run: pip3 install html5validator 
      - run: gem install --no-document html-proofer
      - run: ./proof_html.sh


