name: build_website
run-name: Build, test and deploy (on main)
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6' 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: ./update.sh
      - run: rm -rf _cases/3000 _cves/CVE-3000-*
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - run: pip3 install html5validator 
      - run: gem install --no-document html-proofer
      - run: ./proof_html.sh
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: _site/**
          retention-days: 1
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/github_action' || github.ref == 'refs/heads/main'"
    steps:
      - name: Download html
        uses: actions/download-artifact@v3
        with:
          name: html
      - run: ls
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: htdocs/csirt-divd-nl2
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY_CSIRT }}
