name: build_website
run-name: Build, test and deply website
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - user: actions/setup-ruby@v1
      - run: bundle install